# Generated by Django 5.2 on 2025-04-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[("ordinary", "Обычная"), ("express", "Экспресс")],
                default="free",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[("online", "Онлайн"), ("someone", "При получении")],
                max_length=10,
            ),
        ),
    ]
