# Generated by Django 5.2 on 2025-04-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_order_delivery_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("ordinary", "Обычная"),
                    ("express", "Экспресс"),
                    ("free", "Бесплатная"),
                ],
                default="ordinary",
                max_length=10,
            ),
        ),
    ]
