# Generated by Django 5.2 on 2025-04-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_order_delivery_type_alter_order_payment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[("ordinary", "Обычная"), ("express", "Экспресс")],
                default="ordinary",
                max_length=10,
            ),
        ),
    ]
