# Generated by Django 5.2 on 2025-04-08 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="avatar",
            options={"verbose_name": "Avatar", "verbose_name_plural": "Avatar"},
        ),
        migrations.AlterField(
            model_name="avatar",
            name="src",
            field=models.ImageField(
                default="app_users/avatars/default.png",
                upload_to="app_users/avatars/user_avatars/",
                verbose_name="link",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile",
                to="api.avatar",
                verbose_name="Аватар",
            ),
        ),
    ]
